// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2025-07-15",
  devtools: { enabled: false },
  app: {
    head: {
      htmlAttrs: { lang: "zh-CN" },
      title: "PanHub · 全网最全的网盘搜索",
      titleTemplate: "%s · PanHub",
      meta: [
        {
          name: "viewport",
          content:
            "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover",
        },
        {
          name: "description",
          content:
            "PanHub：聚合阿里云盘、夸克、百度网盘、115、迅雷等平台的全网最全网盘搜索工具，实时检索分享资源，免费、快速、无广告。",
        },
        {
          name: "keywords",
          content:
            "网盘搜索, 阿里云盘, 夸克, 百度网盘, 115, 迅雷, 资源搜索, 盘搜, panhub, 网盘聚合搜索",
        },
        { name: "theme-color", content: "#111111" },
        { property: "og:type", content: "website" },
        { property: "og:site_name", content: "PanHub" },
      ],
      link: [{ rel: "icon", type: "image/x-icon", href: "/favicon.ico" }],
    },
  },
  nitro: {
    // 根据环境变量动态选择部署预设：
    // - cloudflare-module（默认，用于 Cloudflare Workers）
    // - node-server（用于 Docker/自托管 Node）
    // - vercel（用于 Vercel 平台）
    // 优先使用平台内置变量自动识别，无需手动配置 NITRO_PRESET
    // - Vercel: process.env.VERCEL 存在
    // 其余场景：若显式提供 NITRO_PRESET 则使用，否则默认 cloudflare-module
    preset: process.env.VERCEL
      ? "vercel"
      : process.env.NITRO_PRESET || "cloudflare-module",
    prerender: {
      routes: ["/"],
    },
  },
  routeRules: {
    "/": { swr: 3600 },
  },
  runtimeConfig: {
    // server-only
    defaultChannels: [
      "tgsearchers3",
      "yunpanxunlei",
      "tianyifc",
      "BaiduCloudDisk",
      "txtyzy",
      "peccxinpd",
      "gotopan",
      "xingqiump4",
      "yunpanqk",
      "PanjClub",
      "kkxlzy",
      "baicaoZY",
      "MCPH01",
      "share_aliyun",
      "bdwpzhpd",
      "ysxb48",
      "jdjdn1111",
      "yggpan",
      "MCPH086",
      "zaihuayun",
      "Q66Share",
      "NewAliPan",
      "ypquark",
      "Oscar_4Kmovies",
      "ucwpzy",
      "alyp_TV",
      "alyp_4K_Movies",
      "shareAliyun",
      "alyp_1",
      "dianyingshare",
      "Quark_Movies",
      "XiangxiuNBB",
      "NewQuark",
      "ydypzyfx",
      "kuakeyun",
      "ucquark",
      "xx123pan",
      "yingshifenxiang123",
      "zyfb123",
      "tyypzhpd",
      "tianyirigeng",
      "cloudtianyi",
      "hdhhd21",
      "Lsp115",
      "oneonefivewpfx",
      "Maidanglaocom",
      "qixingzhenren",
      "taoxgzy",
      "tgsearchers115",
      "Channel_Shares_115",
      "tyysypzypd",
      "vip115hot",
      "wp123zy",
      "yunpan139",
      "yunpan189",
      "yunpanuc",
      "yydf_hzl",
      "alyp_Animation",
      "alyp_JLP",
      "leoziyuan",
      "AliyunDrive_Share_Channel",
      "aliyunys",
      "Aliyun_4K_Movies",
      "yunpanpan",
      "Quark_Share_Channel",
      "quarkshare",
      "baiduyun",
      "iAliyun",
      "quanziyuanshe",
    ],
    defaultConcurrency: 10,
    pluginTimeoutMs: 15000,
    cacheEnabled: true,
    cacheTtlMinutes: 30,
    public: {
      apiBase: "/api",
      // 用于 sitemap、canonical、OG 等
      siteUrl: "https://panhub.shenzjd.com",
      // 向前端暴露默认频道清单，供 UI 勾选（不会影响服务端私有配置）
      tgDefaultChannels: [
        "tgsearchers3",
        "yunpanxunlei",
        "tianyifc",
        "BaiduCloudDisk",
        "txtyzy",
        "peccxinpd",
        "gotopan",
        "xingqiump4",
        "yunpanqk",
        "PanjClub",
        "kkxlzy",
        "baicaoZY",
        "MCPH01",
        "share_aliyun",
        "bdwpzhpd",
        "ysxb48",
        "jdjdn1111",
        "yggpan",
        "MCPH086",
        "zaihuayun",
        "Q66Share",
        "NewAliPan",
        "ypquark",
        "Oscar_4Kmovies",
        "ucwpzy",
        "alyp_TV",
        "alyp_4K_Movies",
        "shareAliyun",
        "alyp_1",
        "dianyingshare",
        "Quark_Movies",
        "XiangxiuNBB",
        "NewQuark",
        "ydypzyfx",
        "kuakeyun",
        "ucquark",
        "xx123pan",
        "yingshifenxiang123",
        "zyfb123",
        "tyypzhpd",
        "tianyirigeng",
        "cloudtianyi",
        "hdhhd21",
        "Lsp115",
        "oneonefivewpfx",
        "Maidanglaocom",
        "qixingzhenren",
        "taoxgzy",
        "tgsearchers115",
        "Channel_Shares_115",
        "tyysypzypd",
        "vip115hot",
        "wp123zy",
        "yunpan139",
        "yunpan189",
        "yunpanuc",
        "yydf_hzl",
        "alyp_Animation",
        "alyp_JLP",
        "leoziyuan",
        "AliyunDrive_Share_Channel",
        "aliyunys",
        "Aliyun_4K_Movies",
        "yunpanpan",
        "Quark_Share_Channel",
        "quarkshare",
        "baiduyun",
        "iAliyun",
        "quanziyuanshe",
      ],
    },
  },
});
